### ISSUE TITLE
Disable STATIC_URL ?

### ISSUE THREAD

**Issue by benyanke** [tiangolo/uwsgi-nginx-flask-docker#108]
Hello,

I'd like to route all my static assets through flask. Is there a way to stop the functionality provided by `STATIC_URL`? Currently, I have it set in my dockerfile to a long random string, effectively disabling it (since this string would never be reached on the frontend), but this feels like a hack.

![image](https://user-images.githubusercontent.com/4274911/48663773-8c80af00-ea5a-11e8-908c-d584663eb0d6.png)

Is there a better solution?

**Comment by tiangolo** [comment]
That's a good question. But first, is there a reason why you want Flask to serve them directly?

If you need to do anything with them in your code before serving them, they wouldn't really be static.

Check the Flask docs, they recommend having your server serve the static files and using Flask to serve them directly only during development: http://flask.pocoo.org/docs/1.0/quickstart/#static-files

If you need to use Jinja2 templates, that should go into the `templates` directory.

If you need to serve files that somehow you need to read in your Python code first and then serve them (for example, you need to authenticate the user first), you shouldn't put them on `static`, also to not confuse fellow/future developers that work with you or with your code. In that case, you can put those files in any other directory. Let's say, for example, in `./files`.

**Comment by benyanke** [comment]
I'll be the first to admit that my usecase is not entirely normal, but for a number of business reasons, I'm choosing to drive all requests directly through flask, to allow the highest amount of flexibility in the future. One reason is the ability to place static assets at any path easily.

**Comment by tiangolo** [comment]
I just added a lot of tests for all the images, configurations, env vars, etc. To be able to refactor them knowing that I'm not breaking anything.

I'm thinking about refactoring it to allow providing a file in `/app/nginx.conf` and using that instead of the automatically modified/generated one. Would that solve your need?

---

Also, I just created a couple of alternative images with better performance and no default static serving. You might want to check them in the updated [README](https://github.com/tiangolo/uwsgi-nginx-flask-docker). They might do what you need right now.

**Comment by benyanke** [comment]
I will try that next time I'm in for a refactor with this client. Thanks!

**Comment by tiangolo** [comment]
I just finished a big refactor to be able to add this feature on top.

You can now add a file `/app/nginx.conf` and it will be used instead of the generated one.

You can check the docs here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#overriding-nginx-configuration-completely
