### ISSUE TITLE
link to python3.6-alpine3.8 (Dockerfile)?

### ISSUE THREAD

**Issue by kuzeko** [tiangolo/uwsgi-nginx-flask-docker#110]
It seems that the image for tag `python3.6-alpine3.8` listed in the README has the wrong link
and links to https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.6-alpine3.7/Dockerfile

**Comment by kuzeko** [comment]
Great!
I'm not familiar with how things works,
as this anything to do with the fact that the same image is missing on the hub registry?
https://registry.hub.docker.com/v1/repositories/tiangolo/uwsgi-nginx-flask/tags

**Comment by tiangolo** [comment]
Strange, that endpoint doesn't show the current tags. You can see the tags available here:

https://hub.docker.com/r/tiangolo/uwsgi-nginx/tags/

But if you are not very familiar with Docker and Alpine yet, I suggest you use the "standard" non-Alpine version.

Try `python3.6`. 

Python 3.6 is very recent, but not as fresh as Python 3.7, that is not as widely supported yet (many packages will crash).

**Comment by kuzeko** [comment]
Thanks, I see.
I've used docker in the past a lot, but never looked into registry and stuff.
I know I did a `docker pull python3.6-alpine3.8` and it failed.
This is where my search started.

**Comment by tiangolo** [comment]
Hehe, I see.

**Comment by kuzeko** [comment]
Anyway, this issue can be closed I guess. I still cannot pull the 3.6-alpine3.8 but I've pulled the `python3.6-alpine3.7` and I'm working on that.
Not sure if the 3.8 problem is just me. If I can be of any help, please let me know.

In the meantime, thanks for this amazing work! You rock!

**Comment by tiangolo** [comment]
Sorry for the delay! I have been busy creating https://github.com/tiangolo/fastapi

> Anyway, this issue can be closed I guess. I still cannot pull the 3.6-alpine3.8 but I've pulled the python3.6-alpine3.7 and I'm working on that.
> Not sure if the 3.8 problem is just me. If I can be of any help, please let me know.

Docker Hub automated builds were having some issues building the images.

I just added Travis to the whole project, so, the images should be built and pushed a lot faster (20 min, instead of hours) and now I get notifications to be able to check and fix any issue that arises. This should prevent these kinds of problems in the future.

All the images are updated and live now.

> In the meantime, thanks for this amazing work! You rock!

Thanks! :smile: :tada:
