### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by sypho8** [tiangolo/uwsgi-nginx-flask-docker#127]
Just started working with containers, downloaded your docker and tried to use it and that's what happens every time I run the image.

/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by tiangolo** [comment]
It's quite possible that you are in Windows and have git configured to convert line endings from the characters `LF` (line feed) used in Linux and family to `CR LF` (the "carriage return" character followed by "line feed") commonly used in Windows.

Git has an option to auto-convert them when pulling them, but then it sends it as is to Docker, which is Linux, and gets "lost" with the extra `CR` character.

**Comment by RCshare** [comment]
Hi
I'm on windows for developed and create a prestart.sh for add a script.py before my server start. My deployement env is a debian machine. I start my docker on it and got : 

> 
': [Errno 2] No such file or directory
> 

I solved it when i rewrite the prestart.sh with my debian machine, because of  DOS line-endings caused by my windows devellopement post where i created them.

I know this post is closed but i don't know where to share my experience. 
Hope that can help someone !

**Comment by tiangolo** [comment]
Thanks for sharing it @RCshare ! :+1:

**Comment by subrahmanyamjanapamula** [comment]
Thank you, It got worked @**tiangolo.**

**Comment by arbutt1010** [comment]
@topshef I love you, you solved my problem 
Step#1
git clone https://github.com/hashgraph/did-sdk-java.git --config core.autocrlf=input

Step#2
docker build -t apisocial -f ./docker/Dockerfile .

Step#3
docker-compose up --build
And done
In Browser localhost:9090 as I was using 9090 port in docker-compose.yml file

Step#1 is very important, **MUST** RUN ABOVE COMMANDS in **Windows Power Shell**

**Comment by itamarribsilva** [comment]
Thanks a lot!!! It's very usefully"
