### ISSUE TITLE
"server" directive is not allowed here in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by wencha** [tiangolo/uwsgi-nginx-flask-docker#143]
I saw that `start.sh` checked for the existence of `/app/nginx.conf`. I put my `nginx.conf` in the `app` directory, which haves almost exactly the same content as yours but with the `location /static { ... }` block removed and when i run the container it dumps
```
2019/06/28 16:28:56 [emerg] 14#14: "server" directive is not allowed here in /etc/nginx/nginx.conf:1
nginx: [emerg] "server" directive is not allowed here in /etc/nginx/nginx.conf:1
```
I will easily find a workaround but maybe you could modify `start.sh` to make
`cp /app/nginx.conf /etc/nginx/conf.d/nginx.conf`
instead of
`cp /app/nginx.conf /etc/nginx/nginx.conf`
(as that is what the `else` block does with your default conf)
(i finally did `COPY ./nginx-custom.conf /etc/nginx/conf.d` and worked)

Thx for the useful container!

**Comment by esdotzed** [comment]
It depends on which level of config you want to change. If you just need to change the server config, you can do `cp /app/nginx-custom.conf /etc/nginx/conf.d/nginx-custom.conf`, but be careful that don't use the name nginx.conf because it is reserved for the upper level config which is generated by `/uwsgi-nginx-entrypoint.sh`. If you do need to override the upper-level config which is the "REAL" nginx config you can do `cp /app/nginx.conf /etc/nginx/nginx.conf` as provided by the author.

**Comment by tiangolo** [comment]
Thanks for the help here @esdotzed !

I'm glad you solved your problem @wencha !
