### ISSUE TITLE
Using root as user

### ISSUE THREAD

**Issue by Alpus** [tiangolo/uwsgi-nginx-flask-docker#15]
Why do you not change user? Is it secure to run uWSGI with root privileges?

**Comment by tiangolo** [comment]
It runs inside a Docker container so it is not needed to change the user. 

The only things that the container's `root` user has real access to and that he could "break" are the things that live inside that same container. And the only purpose of that container is to run your app. And if your app can break itself, it doesn't need `root` privileges to do that.

So yes, it is OK to use `root` INSIDE a container. Outside a container, it would be a different thing.

**Comment by Alpus** [comment]
Thank you for the answer, but I am still not sure it's a good idea to use `root` privileges. As it written in official Docker best practices page (https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user):

> If a service can run without privileges, use `USER` to change to a non-root user.
...
You should avoid installing or using `sudo` since it has unpredictable TTY and signal-forwarding behavior that can cause more problems than it solves.

Docker is not completely isolated from a host system. It uses different system calls. Besides, there is a `VOLUME` command exists and I think it can cause problems too.

**Comment by tiangolo** [comment]
So, yes, that in the case that you are completely sure your app can run as non-root, I can't know if users' apps can run as non-root. They may need to write to internal directories, etc.

So, the `VOLUME` thing tells Docker to store some specific directory outside the container, so that it can be found after the container dies or is removed. But still, it is an isolated place just for your container handled by Docker (specifically, in `/var/lib/docker/volumes/` ).

There are also named volumes and host volumes. 

The only way I see you could create a security issue would be by mounting a host volume mapping some delicate directory (e.g. the complete root directory: `/`), but that is discouraged for production for several reasons and rarely done.

If a user mounted a host volume, that itself would be the security issue, independent of the image. It would have to be done with special care and the user should be knowing what he's doing.

---

Of course, you are welcome to set and configure a different user in your own image and `Dockerfile` based on this image, that's how this image is intended to be used, as a base image that you can use quickly and adapt if you need to. So, that would be your custom optimization taking into account all the details of your specific application.

And also, I can't enforce setting a different internal user to all the people that use this image, with all the implications of file and directory permissions, file creation permissions, different user IDs in the host and in the container, all the additional instructions, etc. And still, I don't see a specific reason why would I do that.

The same as the official base images this image is based on, Python and Nginx, this one runs as root. All the additional customization can be done by the users depending on their needs.

**Comment by Alpus** [comment]
Ok, thank you for your attention! I think this issue can be closed. :-)

**Comment by tiangolo** [comment]
Cool! Thanks for replying back and closing the issue :smile:
