### ISSUE TITLE
The README on the Docker Hub page is truncated.

### ISSUE THREAD

**Issue by chrisshroba** [tiangolo/uwsgi-nginx-flask-docker#156]
I just noticed the readme at https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/ is cut off at the end, and I thought it was a mistake until I realized that the readme on Github is not truncated, so I assume Docker Hub just has a maximum length. I think it would be helpful to have a note at the end of the readme on Docker Hub saying to check the Github repo to continue reading. I wouldn't have realized this if I hadn't decided to open an issue for it. (PS, thanks for the great image!)

**Comment by tiangolo** [comment]
Thanks! I hadn't noticed that. I didn't know Docker Hub did that :thinking: 

The problem is that the Docker Hub version is done automatically from the GitHub version, so there isn't a way to separate both versions.

The good thing is that the GitHub repo is at the top, so people can go to it directly when coming from Docker Hub.
