### ISSUE TITLE
Advice to tune performance 

### ISSUE THREAD

**Issue by frmsaul** [tiangolo/uwsgi-nginx-flask-docker#168]
I often get the error `RuntimeError: can't start new thread` when running this container in production (facing about 30qps). I'm wondering if there are any trivial ways to increase the number of threads available to flask? Any configurations that one could quickly modify?

**Comment by tiangolo** [comment]
If you need more performance you might benefit from https://github.com/tiangolo/meinheld-gunicorn-flask-docker

And if you need more performance you might benefit from switching over to FastAPI.

Otherwise, you might check the docs to finetune the uWSGI configs in the main README: https://github.com/tiangolo/uwsgi-nginx-flask-docker

And the uWSGI docs: https://uwsgi-docs.readthedocs.io/
