### ISSUE TITLE
How could I fixed the dockerfile setting?

### ISSUE THREAD

**Issue by aleonchen** [tiangolo/uwsgi-nginx-flask-docker#17]
Yesterday, I build a new dockerfile with my python project as usual. But when I start it up, the static files all broken down.

After some time debugging I found the static file path is not config as usual.

I use the COPY in dockerfile building to change the nginx static file path.
But now it did not working.
I try some other ways, it was still not working too.

Suddenly, I realize that maybe there is some thing wrong in the entrypoint.sh

Aha, you have change the static file config to ENV in docker file.

So I fix it following the instruction.

But I am worry about that if it will change some way sometimes in the future.

So my question is how could I get a fixed dockerfile settings but not auto update with the repository?

Thank you.

**Comment by tiangolo** [comment]
When you start a new project it will use the latest version. And normally, when there are changes, those would include bug fixes and improved features. If you have a running project it won't suddenly "update" unless you stop and destroy your container and run a new one. But even if you stop and restart a container, it won't change. So, if you have something in production, it won't change unless you rebuild the image.

If you create a new project, it will use whatever is the current version. So, there could be changes.

Still, if you were using one of the deprecated tags, you should have seen quite some messages in the logs warning you about the changes. I did my best effort to make sure it was as clear as possible that there were changes.

---

This time, there were a lot of changes, that improve several things and allow having several additional configurations. For example, you can set the maximum uploaded file with just an env var. Or if you needed to use a different directory structure, you could do it with an env var too (before, you would have to understand, modify and replace several files). Also, now there's support for Python 3.6.

---

I'm sorry for the inconvenience. :disappointed:  That's also why I'm now using fixed Python version tags, to reduce the possible problems when the `latest` tag starts pointing to `python3.6` instead of `python2.7`. That way, if for example, someone is using a specific tag with `python2.7`, it won't break once the `latest` points to `python3.6`, or maybe a future `python3.7`, as he will be using specifically `python2.7`.

---

I wouldn't suggest you using a fixed version that is frozen in time for new projects. You would be missing any possible updates, like new versions of uWSGI or Nginx, with speed improvements, etc.

I would suggest you to, if you are having issues that don't seem related to your code, check the repo to see if there are any changes.

---

I publish major changes as "releases". So you could create an account in [Sibbell](https://about.sibbell.com/) and "star" this repo and then you would receive automatic notifications in your email with any possible change.

On the other hand, this was a big and important refactor of the code, that made it more robust, simple and configurable. But this kind of major upgrades doesn't happen easily (actually, this is the first major change since the project started). So this specific situation is quite rare and I wouldn't expect it to happen soon again. :smiley:

**Comment by aleonchen** [comment]
First of all, great thanks for your reply, you are a nice man.

This version is a great update for me to get new features and more  flexible configurations such as the static folder.

Your project help me a lot to setup a flask web app.

You advice is great and I will continue updating the docker file in the new project with it.

The Sibbell is a good solution for me to tracking the updates that is what I need.

Thank you for setup this great project again.

**Comment by tiangolo** [comment]
Great! I'm happy to help :smiley:
