### ISSUE TITLE
E: Unable to locate package openjdk-8-jdk

### ISSUE THREAD

**Issue by adnan33** [tiangolo/uwsgi-nginx-flask-docker#187]
Hello. Thanks for your great work on this. I had used the python3.6 image for my app which needed openjdk-8. It worked previously but after recent update to the base image, it stopped working and gives out this error. The host os is centos-7.7. 
Please help me sort out this issue. Thank You.

**Comment by tiangolo** [comment]
Hey, check the note here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#supported-tags-and-respective-dockerfile-links

You can pin the image version with a date from when it was working (probably an older Debian version).

Otherwise, you can update your Dockerfile to install your required dependencies.

**Comment by adnan33** [comment]
I believe i was using [tiangolo/uwsgi-nginx-flask:python3.6-2020-05-09](https://hub.docker.com/layers/tiangolo/uwsgi-nginx-flask/python3.6-2020-05-09/images/sha256-98970564aeb7b5e636a0411936e61c02e81b19d5f93a4cd01715b6a690e6790b?context=explore) for my app.

**Comment by adnan33** [comment]
Closing the issue as app functionality is restored using an [earlier](https://hub.docker.com/layers/tiangolo/uwsgi-nginx-flask/python3.6-2020-05-07/images/sha256-77d6efbd5348d4e0960f2ae4796f06f28a313800123527c598433218314f0007?context=explore) version.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
