### ISSUE TITLE
Adding own domain and SSL certificates

### ISSUE THREAD

**Issue by pu22** [tiangolo/uwsgi-nginx-flask-docker#20]
Hi,

first of all thank you very much for this image. It has made everything so much easiert. I don't know if that belongs here but could you give me a short description of how I can add SSL certificates and how I can use my own domain? Currently I just access the Flask app by opening the IP adress of my Ubuntu server.

Thanks a lot for your time.

**Comment by tiangolo** [comment]
I'm glad it's helping you!

---

The best way to achieve that is using what they call "TLS termination". A proxy server on top of your container, independent of it. 

By making it an independent container it is easier to install and update certificates, probably with Let's encrypt. 

And also, it allows you to have more than one app in a specific server / IP address. Because only one thing (container) can server TLS in a server. But if you have a proxy that handles that, the proxy can have the certificates for more than one app and serve each one of them with their correct certificates.

If you have a simple installation / app, I would try first with [`Traefik`](https://github.com/containous/traefik). It even has Let's encrypt integration and is made to be integrated with other systems as Docker.

But if you have a big deployment, you might want to try Rancher for orchestration, it has a Let's encrypt stack that you can use to generate certificates and then you can use one of the integrated load balancers (created from the web UI) to be the TLS termination proxy (they are actually based on HAproxy).

The other two options apart from Traefik are Nginx and HAProxy, but I would try with Traefik first, as it is made to be easier to use with Docker stacks, Let's encrypt integration, etc.

**Comment by pu22** [comment]
Thanks a lot for the details. In the comments on Docker Hub someone suggested to add the SSL certificates into the Docker image. Is that also an option? I could also add my domain name to the config file. Thank you.

**Comment by tiangolo** [comment]
Ah! About adding your own domain, you need a publicly accessible server, let me suggest [Linode](https://www.linode.com/?r=8ee6f60b2ddb258bba3fefe264771bca3660fb97), they have the best "bang for the buck".

You need to buy a Domain Name, let me suggest [Name](https://www.name.com/referral/16bb2). Best bang for the buck too.

From the name Name settings, you would set your DNS to point to Linode (your Linode account will tell you how).

Then, from your Linode account, in the DNS Manager, you would set your domain to point to your server's IP.

Then, on your server, you would have something listening for connections to a specific host (to your domain) and will answer with the contents of your app. That could be Traefik, for example.

Your Flask app doesn't necessarily need to know which domain is accessing it. Either way, configuring it in your Flask app won't affect how people access it, it depends on your browser, the DNS records, etc.

*Note*: The links provided have my referral code ;)

---

About adding SSL certificates into the Docker image is possible, and the image exposes the port 443 in case you want to do it, but I wouldn't recommend it, I would say it's a bad idea.

**Comment by pu22** [comment]
Thanks a lot for your detailed answer. I already have a server and my Flask app is running there perfectly fine thanks to your amazing image. However at the moment I'm accesing the app by typing in my servers IP in the web browser. In only have this app running on my server nothing else. What I don't understand is why do I need another proxy on top of that when nginx is already included in your image. I understand the need for something like Trafik if there are multiple apps running on my server. Thanks again for your time.

**Comment by tiangolo** [comment]
Because Traefik will take care of renewing the Let's encrypt certificates every 3 months when they get stale, and it will take care of redirecting the traffic for the Let's encrypt challenges, etc. Otherwise, it is a lot of code you have to handle internally in the image, adds a lot of complexity, etc.

And, although it could seem simple, TLS and certificate handling are topics complex enough to deserve a decoupled part of the system to handle it. For separation of concerns, etc.

Still, the main reason is that you have to get the certificates (Let's encrypt), redirect the necessary traffic for the challenges to be able to obtain them, then renovate them every time they expire (every 3 months), and install them correctly. All those steps are better handled (and are handled automatically) by something like Traefik.

**Comment by pu22** [comment]
Alright thank you. Now I've understood it. I even manged to already set it up. There is only one more open question. Is such a setup still efficient in terms of performance? To me it seems a bit redundant to use two proxies. Thanks again for your time.

**Comment by tiangolo** [comment]
The bottleneck is almost always your app code and Python, not your proxies on top, those a written in C (Nginx) and Go (Traefik). So, the possible performance penalty would be negligible compared to the performance penalty from your app code.

**Comment by tiangolo** [comment]
@pu22 Did you solve your problem? Can we close this issue?

**Comment by pu22** [comment]
Thanks again for your time and help.
