### ISSUE TITLE
Can't disable request logging

### ISSUE THREAD

**Issue by nicbou** [tiangolo/uwsgi-nginx-flask-docker#205]
I run this app behind a reverse proxy that already logs requests. I don't want to log requests, because the logs should be for useful log messages. I've tried different things, but I just can't disable the logs!

Sample message:
```
172.20.0.X - - [05/Nov/2020:13:32:00 +0100] "GET /reminders HTTP/1.0" 200 3255 "-" "Mozilla/5.0 (...) Gecko/20100101 Firefox/82.0" "172.20.0.1"
```

I tried:

* Adding `disable-logging = true` to my uwsgi.ini. No effect. The config change appears in the start messages.
* Setting `app.logger.disabled = True` after the `app = Flask(__name__)` call.
* Disabling python logging entirely with `logging.getLogger('root').disabled = True`. It works for everything except request logs!

It should be simple, but for the life of me, I can't figure it out!

**Comment by nicbou** [comment]
Wait, I figured it out. The logs come from nginx. The parent image (uwsgi-nginx) symlinks the access and error logs to stdout and stderr. Deleting that symlink fixes the issue. I simply added this line to my dockerfile:

```
RUN rm /var/log/nginx/access.log

# If you don't want error logs, uncomment this:
# RUN rm /var/log/nginx/error.log
```

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:

**Comment by JeremyCanfield** [comment]
Spot on question and answer.

I just wanted to mention that instead of using the rm (remove) command in Dockerfile I used the unlink command to remove the symbolic link from /var/log/nginx/access.log to /dev/stdout and to remove the symlink from /var/log/nginx/error.log to /dev/stderr.

`RUN unlink /var/log/nginx/access.log`
`RUN unlink /var/log/nginx/error.log`

After I create a container from the Docker image, now events are still being appended to access.log and error.log but the events in access.log and error.log are not being redirected to stdout and stderr, cleaning up the output returned by the Docker logs command.

`~]$ sudo docker exec my-container ls -l /var/log/nginx`
`-rw-r--r--. 1 root root 3709 May 20 03:43 access.log`
`-rw-r--r--. 1 root root    0 May 20 03:43 error.log`

Bonus points - I am using the Amazon Web Services log driver to append the Docker logs to AWS CloudWatch, and this really cleaned up the CloudWatch logs, where the logs now only have the events we really care about, and not all of the nginx GET requests.
