### ISSUE TITLE
Alpine Linux

### ISSUE THREAD

**Issue by claygorman** [tiangolo/uwsgi-nginx-flask-docker#21]
Have you considered using alpine linux?

**Comment by tiangolo** [comment]
Yes, like an additional option, not like a replacement for the standard base images.

The reasons to have Debian as the main official base image are these:

* Users will be more familiar with a Debian image as most of the official images use it and it is part of [Docker best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#from). It's more probable for someone to know how to use `apt` than to use `apk`, etc.

* Image size is not that much of a constraint, as "disk space is cheap", but mostly because, as Docker images are arranged in layers, it's very probable for users to already have all the base Debian layers downloaded if they are using any other official image (like Postgres, MySQL, Redis, etc).

Given that, Pull Requests are always welcome. The place to add Alpine as an alternative would be the Docker image in https://github.com/tiangolo/uwsgi-nginx-docker which is the base image for this one.

**Comment by claygorman** [comment]
Thanks for the explanation. You have a few good points there. I do not personally think that making an alpine linux version is make or break at all but was more curious what your take on it was.

A very good explanation and some references to go with it :)

I appreciate you taking the time as a maintainer.

**Comment by tiangolo** [comment]
Thanks for replying back and thanks for closing the issue :+1:
