### ISSUE TITLE
Vulnerabilities in tiangolo/uwsgi-nginx-flask:python3.8

### ISSUE THREAD

**Issue by asusatapathy** [tiangolo/uwsgi-nginx-flask-docker#216]
Hi Team,

Am getting around 2 Critical and more than 32 high vulnerability issues in the base image : tiangolo/uwsgi-nginx-flask:python3.8

Attached screen shots for your reference.
<img width="1083" alt="Screenshot 2021-02-10 at 7 22 02 PM" src="https://user-images.githubusercontent.com/66781416/107518795-70d2c780-6bd5-11eb-863d-1eae1e038de0.png">
<img width="1074" alt="Screenshot 2021-02-10 at 7 24 10 PM" src="https://user-images.githubusercontent.com/66781416/107518931-9a8bee80-6bd5-11eb-82c2-8ae76462a4fb.png">

**Comment by James-LeHa** [comment]
Raising additional vulnerabilities identified with Trivy container scanning.

28 Critical   vulnerabilities:
    - CVE-2019-19948
    - CVE-2019-19949
    - CVE-2019-20367
    - CVE-2021-33574
    - CVE-2020-0452
    - CVE-2020-13112
    - CVE-2021-20231
    - CVE-2021-20232
    - CVE-2020-15180
    - CVE-2021-3177
    - CVE-2019-25032
    - CVE-2019-25033
    - CVE-2019-25034
    - CVE-2019-25035
    - CVE-2019-25038
    - CVE-2019-25039
    - CVE-2019-25042
    - CVE-2018-25009
    - CVE-2018-25010
    - CVE-2018-25011
    - CVE-2018-25012
    - CVE-2018-25013
    - CVE-2018-25014
    - CVE-2020-36328
    - CVE-2020-36329
    - CVE-2020-36330
    - CVE-2020-36331
    - CVE-2019-18814

Anyway the community could help in tackling some of these? This is a great image used by many projects/companies.

**Comment by aspirina765** [comment]
Snyk : 

Testing uswgi-nginx-flask:latest...

✗ Medium severity vulnerability found in e2fsprogs/libcom_err
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-ALPINE37-E2FSPROGS-493456
  Introduced through: e2fsprogs/libcom_err@1.43.7-r0, krb5-conf/krb5-conf@1.0-r1
  From: e2fsprogs/libcom_err@1.43.7-r0
  From: krb5-conf/krb5-conf@1.0-r1 > krb5/krb5-libs@1.15.4-r0 > e2fsprogs/libcom_err@1.43.7-r0
  Image layer: Introduced by your base image (python:3.6.8-alpine3.7)
  Fixed in: 1.43.7-r1

✗ High severity vulnerability found in expat/expat
  Description: XML External Entity (XXE) Injection
  Info: https://snyk.io/vuln/SNYK-ALPINE37-EXPAT-453374
  Introduced through: expat/expat@2.2.5-r0, .python-rundeps@0, python2/python2@2.7.15-r3, python3/python3@3.6.9-r1
  From: expat/expat@2.2.5-r0
  From: .python-rundeps@0 > expat/expat@2.2.5-r0
  From: python2/python2@2.7.15-r3 > expat/expat@2.2.5-r0
  and 1 more...
  Image layer: Introduced by your base image (python:3.6.8-alpine3.7)
  Fixed in: 2.2.7-r0

✗ High severity vulnerability found in expat/expat
  Description: Out-of-bounds Read
  Info: https://snyk.io/vuln/SNYK-ALPINE37-EXPAT-489399
  Introduced through: expat/expat@2.2.5-r0, .python-rundeps@0, python2/python2@2.7.15-r3, python3/python3@3.6.9-r1
  From: expat/expat@2.2.5-r0
  From: .python-rundeps@0 > expat/expat@2.2.5-r0
  From: python2/python2@2.7.15-r3 > expat/expat@2.2.5-r0
  and 1 more...
  Image layer: Introduced by your base image (python:3.6.8-alpine3.7)
  Fixed in: 2.2.7-r1

✗ Critical severity vulnerability found in sqlite/sqlite-libs
  Description: Out-of-bounds Read
  Info: https://snyk.io/vuln/SNYK-ALPINE37-SQLITE-458200
  Introduced through: sqlite/sqlite-libs@3.25.3-r0, .python-rundeps@0, python2/python2@2.7.15-r3, python3/python3@3.6.9-r1
  From: sqlite/sqlite-libs@3.25.3-r0
  From: .python-rundeps@0 > sqlite/sqlite-libs@3.25.3-r0
  From: python2/python2@2.7.15-r3 > sqlite/sqlite-libs@3.25.3-r0
  and 1 more...
  Image layer: Introduced by your base image (python:3.6.8-alpine3.7)
  Fixed in: 3.25.3-r1

✗ Critical severity vulnerability found in bzip2/libbz2
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-ALPINE37-BZIP2-452717
  Introduced through: bzip2/libbz2@1.0.6-r6, .python-rundeps@0, freetype/freetype@2.8.1-r4, python2/python2@2.7.15-r3, python3/python3@3.6.9-r1
  From: bzip2/libbz2@1.0.6-r6
  From: .python-rundeps@0 > bzip2/libbz2@1.0.6-r6
  From: freetype/freetype@2.8.1-r4 > bzip2/libbz2@1.0.6-r6
  and 2 more...
  Image layer: Introduced by your base image (python:3.6.8-alpine3.7)
  Fixed in: 1.0.6-r7



Package manager:   apk
Project name:      docker-image|uswgi-nginx-flask
Docker image:      uswgi-nginx-flask:latest
Platform:          linux/amd64
Base image:        python:3.6.8-alpine3.7

Tested 63 dependencies for known vulnerabilities, found 5 vulnerabilities.

Base Image              Vulnerabilities  Severity
python:3.6.8-alpine3.7  6                3 critical, 2 high, 1 medium, 0 low

Recommendations for base image upgrade:

Alternative image types
Base Image                    Vulnerabilities  Severity
python:3.11-rc-slim-bullseye  49               0 critical, 1 high, 0 medium, 48 low
python:3.7-slim               49               0 critical, 1 high, 0 medium, 48 low
python:slim                   49               0 critical, 1 high, 0 medium, 48 low
python:3.10.5-slim-buster     84               0 critical, 1 high, 0 medium, 83 low

Alpine 3.7.1 is no longer supported by the Alpine maintainers. Vulnerability detection may be affected by a lack of security updates.

For more free scans that keep your images secure, sign up to Snyk at https://dockr.ly/3ePqVcp

**Comment by tiangolo** [comment]
These are things related to the underlying base images and not really this one, right? Probably better to check and report them in the respective base images. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
