### ISSUE TITLE
Default uwsgi.ini overrides settings in the custom configuration

### ISSUE THREAD

**Issue by ronlut** [tiangolo/uwsgi-nginx-flask-docker#41]
Hi, first of all, thank you for your great work!

I found a problem while deploying my app, which has a custom uwsgi.ini inside the `app` folder, on top of this docker image.
I want to set a different value for `cheaper`, but while changing all other cheaper-related settings (`cheaper-initial`, `cheaper-step`) works, settings `cheaper=5` doesn't because the default `uwsgi.ini` (/etc/uwsgi/uwsgi.ini) sets `cheaper = 2`.

I validated this issue by overriding `/etc/uwsgi/uwsgi.ini` with my custom settings.
I guess the same will happen by trying to set `processes` (which is also declared in the deault `uwsgi.ini`) to a value different from 16.

I would be happy to create a PR fixing this issue, but I need some guidance on the way it merges the 2 configs (default and the custom one in `/app`) 🙂

**Comment by tiangolo** [comment]
I'm happy it has helped you.

I'll check it soon.

**Comment by lironmo** [comment]
same problem the application uwsgi.ini failed to override cheaper value from /etc/uwsgi/uwsgi.ini.

quick solution in to change the ini file using copy command.

**Comment by tiangolo** [comment]
The problem came from the base image: https://github.com/tiangolo/uwsgi-nginx-docker. 

In the latest commit, the `cheaper` and `processes` configs are now in environment variables (instead of in the global config file) so that they can be overwritten by your app config file.

You should be able to pull the latest version of the image, rebuild your image and it should work.

Please let me know how it goes if you test it! :smile:

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue.
