### ISSUE TITLE
Can not access MongoDB on host

### ISSUE THREAD

**Issue by kingname** [tiangolo/uwsgi-nginx-flask-docker#61]
I use tag:python3.6 to run a flask app.

my code is like below:

```
from flask import Flask
import pymongo


app = Flask(__name__)
connect = pymongo.MongoClient('mongodb://127.0.0.1:8800')
db = connect.testdb
handler = db.testcol

@app.route('/')
def index():
    return str(handler.find().count())


if __name__ == '__main__':
    app.run(host='0.0.0.0', prot=80, debug=False)
```

My MongoDB is running in the host machine. so I launch a docker with the parameter `--network host`,  as I use the `host mode`, there is no necessary to expose port.

The problem is that I find the flask can not connect to the MongoDB. The log show: 
```
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
```

However, when I `docker exec -it container /bin/bash`

and then use this command to run the flask app:

```
export FLASK_APP=main.py
flask run --host=0.0.0.0 --port=8800
```

then everything is correct, I can visit the url in my broswer and the access to mongodb work as charm.

**Comment by tiangolo** [comment]
First, why are you using a host MongoDB instead of a Docker MongoDB container?

I would suggest you try doing that, as it provides several advantages.

In this command:

```bash
flask run --host=0.0.0.0 --port=8800
```

...you are telling Flask to override the port that you are declaring to be the MongoDB port and bind to it. I don't see how that could work.

Also, you are declaring MongoDB to be using port `8800` in this line:

```Python
connect = pymongo.MongoClient('mongodb://127.0.0.1:8800')
```

...but by default MongoDB listens on port `27017`, so, unless you explicitly told MongoDB to run on port `8800`, it will be running on `27017`.

I haven't needed to use a MongoDB host instance instead of a Docker one, so I don't know if that might be affecting. Again, I encourage you to try using a MongoDB in a Docker container. If you have a container `my_mongodb`, that line would probably be:

```Python
connect = pymongo.MongoClient('mongodb://my_mongodb:27017')
```

**Comment by kingname** [comment]
I use mongodb in host because it is more convenient to persist data into hard disk.
 
I surely have changed the port of MongoDB. 

OK I will try.

**Comment by tiangolo** [comment]
Check out the Docker volumes documentation: https://docs.docker.com/storage/volumes/

You can make it persist volumes in a named volume handled by Docker that stores the data directly in the host, or you can even map a local directory to an internal directory if you want to, for example, put that in an external hard disk. The first option is the recommended one.

But check the volumes docs, that probably solves the persistence problem and then you can leverage all the advantages of Docker.

**Comment by kingname** [comment]
Sure, use mongodb in docker could solve the problem. 

But why flask in docker could not access mongodb in host only when the flask app launched by your docker command? 

When I enter the interactive bash of the launched docker and launch the flask app manually, every thing work as expected?

**Comment by tiangolo** [comment]
Actually, I don't know why it even worked with Flask alone. It shouldn't, as you are overwriting the port of MongoDB with your Flask command. I mean, it shouldn't even "work as expected", given the code you showed me.

The problem is that I don't have a way to replicate your exact environment and understand how it's configured with all the details. I can replicate a Docker based stack because it's made to be easily replicable. But a custom host installation, in some specific operating system and some specific additional packages, etc, becomes hard to debug and find any issue, it becomes what they call a very unique ["Snowflake Server"](https://martinfowler.com/bliki/SnowflakeServer.html).
