### ISSUE TITLE
how to use https instead of http without much work

### ISSUE THREAD

**Issue by aravindarc** [tiangolo/uwsgi-nginx-flask-docker#63]
Thanks Tiangolo for the image, it's great.

I have a flask application that uses the webcam, and you can only access the webcam through a https connection, in development I used ssl_context='adhoc' in the flask code, how to do it in the docker container, I don't want certs or anything just a simple https connection. The app is going to be deployed just in the LAN.

**Comment by tiangolo** [comment]
Here's the thing, HTTPS is not simple. Not at all. That's somewhat confusing at first as it seems as if it was just a modification to HTTP.

Actually, HTTPS is a whole layer of stuff happening before HTTP goes on. And on top of that layer, HTTP goes without modification. But all that stuff that has to happen before HTTP has to be handled.

---

You have to have certificates for HTTPS.

For the certificates, you have these options:

* Generate HTTPS certificates yourself using `openssl`, etc. This is the easiest option.

  That would mean that your users would see a "Not secure HTTPS" big warning, and they would have to find a little option in the corner with "continue anyway".

* Generate the certificates using a domain name you own in a public server, using Let's encrypt. And then you can copy those certificates for your local network if you don't want your app to be open in the public internet.
  * Then you would have to configure (or have the IT team do it) your LAN to point that domain to your local network, to your machine.
  * Those certificates are short-lived, they have about 3 months, so you have to automatize all the process.

    With that, your users won't see the "Not secure HTTPS" warning. But you would have to do all those steps.

---

After getting your certificates, you need to use them. My suggestion is to have a separate container handling the certificates and HTTPS that then redirects the communication to your container, instead of handling the certificates in your container. That's called "SSL termination" and is considered a "best practice" in many places.

You can very easily do that with [Traefik](https://github.com/containous/traefik). It is made to be integrated with Docker easily. Also, it can handle generating the certificates via Let's Encrypt.

If you want to see how Traefik can handle redirection, HTTPS and how easily it is configured (using Docker labels in your other containers) check: https://github.com/tiangolo/full-stack

**Comment by aravindarc** [comment]
Thank you Tiangolo for your fast and elaborate comment, really appreciate it.

**Comment by tiangolo** [comment]
You're welcome! Thanks for reporting back and closing the issue.
