### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by abstiles** [tiangolo/uwsgi-nginx-flask-docker#66]
When using a service built on an image based on one of these containers, I get warning messages about "supervisord" and "uWSGI" running as root. In addition, it seems a common piece of security advice for docker-based services is that they should not run as root. Can the design of these docker images be reworked so that the containerized application does not require running as root?

**Comment by tiangolo** [comment]
The warning is because those packages were designed to be run in a full machine, not a Docker container. A container is an isolated, sand-boxed environment that doesn't have access to the rest of the machine, only the access you provide it via Docker.

As an example, check the official images for Debian, Python, NodeJS, CouchDB, MongoDB, and many others.

It is a common piece of security advice to do not run as root many packages, in full system environments. To do not risk that a privileged component in the system could risk the other components.

In the case of a Docker container, the only component is the application itself. So, the only thing that being root inside the container could affect is the same application, which still needs to be able to use all its own code, so, being root or not would not change much.

The situation where things could get dangerous is mounting host volumes (which is a bad practice), especially if you mount a privileged directory.

Also, handling users and permissions inside a container would require a lot of effort by the users, the developers, configuring and handling files and permissions. While Docker by itself is already providing a lot more isolation and security than what a raw host installation ever could.

If you find a specific generic use case that demonstrates a security issue, please let me.

**Comment by abstiles** [comment]
I appreciate your reasoning about this, but you seem to be disagreeing with a lot of the wisdom I'm encountering about security and containers. A quick google search easily turns up several blog posts warning against running as root:

* https://opensource.com/article/18/3/just-say-no-root-containers
* https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b
* http://blog.dscpl.com.au/2015/12/don-run-as-root-inside-of-docker.html
* (and a stack exchange answer) https://security.stackexchange.com/a/176350

It does appear that the *general consensus* on security in Docker is that one should avoid running their processes as root. You may disagree about the risks, but I cannot ignore the advice I see everywhere. I would urge you to reconsider your conclusion on this topic in light of these arguments.

**Comment by tiangolo** [comment]
> I appreciate your reasoning about this, but you seem to be disagreeing with a lot of the wisdom I'm encountering about security and containers.

I think it depends on the wisdom you look for in your searches. And what does "security" mean each time. You could also end up adding SELinux or AppArmor inside your containers and that would add security. But do you really need that specific security?

What would that secure? It would make sure that your code doesn't break the parts that don't belong to him in the environment it is running. But when the only parts that are in the environment it is running belong to him, most of the additional security measures are protecting nothing.

The only risk is that your code hacks itself. But you know how to write your code well, so it won't. On the other side, in many cases, many of those additional security measures actually end up breaking the code that you want to have running, because those measures thought they should "protect" you from your own code.

> A quick google search easily turns up several blog posts warning against running as root

I would recommend you don't base your decisions on quick Google searches, you could end up running containers based on Phushion because it appears high in the searches while Solomon Hykes himself disagrees with it.

Also, please read those articles. I just did. Most of them say "you shouldn't run as root because you shouldn't". 

The first one comes from RedHat which has never played well with Docker. They also seem to try to make everyone adapt to how they decide to make things, and put SELinux everywhere and make everyone adapt to it but never explains why, just that "you should". There's a long-standing issue with their Firewall (using CentOS) randomly blocking Docker, and at some point I also found an issue that makes the firewall have non-deterministic states, resetting its rules after restarting. I reported it and apparently they fixed it, about a year ago. But it seems to keep happening (by the comments in the original issue). That specific article says "you shouldn't run as root because I already told you so".

The other articles referenced there say that if someone has access to the privileged filesystem they can own the machine, but in the next referenced articles it comes back to clarify that Docker drops support for most of the capabilities and that the required volumes are mounted read-only. They also say that if there's a vulnerability in the kernel directly, your container could take advantage of it.

It's a very, very specific and low probability security risk. I would say that if you really want to be completely secure against that, you should use virtual machines and not Docker. Also, the code that could take advantage of that and break something is your own code, that you are putting inside the container.

The next article basically says "you shouldn't because you shouldn't".

And the next one says that if you mount a volume with `-v /:/rootfs` then you can break everything from inside Docker. Of course! You would never mount the full filesystem inside a container. Actually, you would never mount a host volume at all inside a production container, only for development. The same way you wouldn't run `sudo rm -rf /`. But because you can run `sudo rm -rf /` doesn't mean that you should eliminate the existence of `sudo rm`.

The Stack Exchange has 1 vote. Says: "root in container is a risk. It still interacts with the kernel as root. And if an application manages to break out of container, it has root privileges on host.". That's clearly said by someone who doesn't know how Docker works very well. It also says "...I am not really familar with user namespacing". So I wouldn't necessarily take advice about namaspaces (Docker) from him.

> It does appear that the general consensus on security in Docker is that one should avoid running their processes as root.

Please, don't assume general consensus from a quick Google search.

---

> You may disagree about the risks, but I cannot ignore the advice I see everywhere. I would urge you to reconsider your conclusion on this topic in light of these arguments.

Of course, please do so. All that is needed to run as non-root actually has to be done on your side. I cannot enforce everyone to use non root, use a specific username, adapt their code to the specific username I decided, change the permissions and ownership of all the code and relevant files to that specific username, that they don't have in their machine and add all the specific user handling, permission changing, etc inside their own `Dockerfile`s. But you can. 

You have to define the username you will use. Copy your code, change the ownership to that user, use a custom entrypoint to make Supervisor, Nginx and uWSGI be run by that specific user you created and change to that user. All the steps have to be done on your `Dockerfile`, as you have to copy, set permissions and ownership and define user there.

**Comment by snixon** [comment]
FWIW: 
The alpine image works just fine if you add:
`uid = uwsgi
gid = uwsgi`
to the bottom of uwsgi.ini

That'll take care of one of your warnings @abstiles

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.

**Comment by KonstantinSchubert** [comment]
> FWIW:
> The alpine image works just fine if you add:
> 
> ```
> uid = uwsgi
> gid = uwsgi
> ```
> to the bottom of uwsgi.ini
> 
> That'll take care of one of your warnings @abstiles

@snixon Wait, but why? Where is this user being created in the docker files?

**Comment by Mierpo** [comment]
How does this project's use of root user in containers take into account things like: https://seclists.org/oss-sec/2019/q1/119

Vulnerabilities like these are unpredictable and can break default security assumptions about root in containers at any time.
The only component at risk is not the application itself. A short guide how to setup a non-root users with your great base image would be welcome.

> Quote:
> The vulnerability allows a malicious container to (with minimal user
> interaction) overwrite the host runc binary and thus gain root-level
> code execution on the host. The level of user interaction is being able
> to run any command (it doesn't matter if the command is not
> attacker-controlled) as root within a container in either of these
> contexts:
> 
>   * Creating a new container using an attacker-controlled image.
>   * Attaching (docker exec) into an existing container which the
>     attacker had previous write access to.
> 
> This vulnerability is **not** blocked by the default AppArmor policy, nor
> by the default SELinux policy on Fedora[++] (because container processes
> appear to be running as container_runtime_t). However, it **is** blocked
> through correct use of user namespaces (where the host root is not
> mapped into the container's user namespace).

**Comment by tiangolo** [comment]
@Mierpo Please read the comments above. Let me copy this section:

All that is needed to run as non-root actually has to be done on your side. I cannot enforce everyone to use non root, use a specific username/UID, adapt their code to the specific username/UID I decided, change the permissions and ownership of all the code and relevant files to that specific username/UID, that they don't have in their machine and add all the specific user handling, permission changing, etc inside their own `Dockerfile`s. But you can.

You have to define the username you will use, with a specific UID. Copy your code, change the ownership to that user, use a custom entrypoint to make Supervisor, Nginx and uWSGI be run by that specific user you created and change to that user. All the steps have to be done on your `Dockerfile` (and your local machine), as you have to copy, set permissions and ownership and define user there.

Also, make sure all your team members are aware of the specific username/UID you created for the project, to enforce them to do all their local setup as well.

**Comment by snixon** [comment]
> @snixon Wait, but why? Where is this user being created in the docker files?

@KonstantinSchubert Looks like in latest the uwsgi user no longer exists. But did exist when I wrote the comment originally.  Probably can swap out to "nobody" for the latest.

```
docker images
---snip---
tiangolo/uwsgi-nginx   python3.6-alpine3.8    927e3b73134b        4 weeks ago         181MB
---snip---

$ docker run -it 927e3b73134b /bin/sh

/app # cat /etc/passwd
---snip---
nobody:x:65534:65534:nobody:/:/sbin/nologin
nginx:x:100:101:Linux User,,,:/var/cache/nginx:/sbin/nologin
uwsgi:x:101:102:uwsgi:/dev/null:/sbin/nologin
---snip---
```

**Comment by rahuledb** [comment]
Thread is little older, but thought this might be useful.

@abstiles You have to create a non root user and give it full access.

In a shell, type below command
```
adduser myuser

# While adding user it will ask for password, enter the desired password
usermod -aG sudo myuser

# Above statement may work in unix/linux, but not in certain OS like CentOS, for that use below command:
usermod -aG wheel myuser
```

And you are done. Now to switch the account type below code:
`su - myuser`

Now for uwsgi you may add socket directly in uwsgi.ini file :
```
socket = 127.0.0.1
uid = myuser
```

Also, if you are using fastcgi-socket, then you may create the socket by python itself:
`python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/tmp/test.sock')"`

Now add this configuration in uwsgi.ini file like :
`fastcgi-socket=/tmp/test.sock`

But before running the uwsgi, you should make sure the user has appropriate permissions to use the socket, check it :
`namei -nom /tmp/test.sock`

This will print below output:
```
f: /tmp/test.sock
 dr-xr-xr-x.     root   root   /
 drwxrwxrwx  root   tmp
 srwxrwxr-x   root    test.sock
```
As myuser do not have permissions, use below command to give it; Although giving full permission is not a right way:
```
chmod 777 /tmp/
chmod 777 /tmp/test.sock
```
If above permission does not work, try below command:
```
chown myuser /tmp/
chown myuser /tmp/test.sock
```
Now you may try running uwsgi, it should work.

**Comment by GilKata** [comment]
> FWIW:
> The alpine image works just fine if you add:
> 
> ```
> uid = uwsgi
> gid = uwsgi
> ```
> 
> to the bottom of uwsgi.ini
> 
> That'll take care of one of your warnings @abstiles
> 
> EDIT 2019-02-14:
> uwsgi is no longer a user in the latest version of this image. `nobody:nobody` works in the same fashion.
> 
> ```
> uid = nobody
> gid = nobody
> ```
@snixon @tiangolo 

I configured the uwsgi.ini file with:
uid = nobody
gid = nobody

But when the server starts, I get the following errors:
group nobody not found.
INFO exited: uwsgi (exit status 1; not expected)

What am I missing here?

**Comment by snixon** [comment]
@GilKata What version are you using? 
I just spun up a quick test using `tiangolo/uwsgi-nginx-flask:python3.8-alpine` with the "Hello World" flask app in the README and the `nobody` user works.

```
[uwsgi]
module = main
callable = app
uid = nobody
gid = nobody
```

```
PID   USER     TIME  COMMAND
    1 root      0:00 {supervisord} /usr/bin/python3 /usr/bin/supervisord
    9 root      0:00 nginx: master process /usr/sbin/nginx
   10 nobody    0:00 /usr/sbin/uwsgi --ini /etc/uwsgi/uwsgi.ini
   11 nginx     0:00 nginx: worker process
   13 nobody    0:00 /usr/sbin/uwsgi --ini /etc/uwsgi/uwsgi.ini
   14 nobody    0:00 /usr/sbin/uwsgi --ini /etc/uwsgi/uwsgi.ini
   23 root      0:00 /bin/sh
   30 root      0:00 ps
```

**Comment by GilKata** [comment]
@snixon I'm using `tiangolo/uwsgi-nginx-flask:python3.7`
Is there a way to make it work not on Alpine? I might add some scientific packages and I know that those packages on python+Alpine don't work well.

**Comment by snixon** [comment]
@GilKata 

I took a look at that image, it looks like the base image uses nobody for uid and nogroup for gid.

So if you wanted to run this way, you would use the following in your uwsgi.ini file:

```
uid = nobody
gid = nogroup
```
HTH

**Comment by GilKata** [comment]
@snixon Perfect, I'll check it out. Thanks Steve!

**Comment by berndkuennen** [comment]
I tried a different approach when trying to get the tiangolo image running on Openshift. The latter runs the pods with a unpredictable non-root uid by default, but inside the container the process #1 still runs with gid=0 which still makes life easier in some places. So I simply made the socket (and some log folders etc.) writeable to the group:
```
[uwsgi]
socket = /tmp/uwsgi.sock
chmod-socket = 660
```
Works fine on Openshift/OKD and on Rancher with pod_security_policy "restricted". Details and a working dockerfile are to be found at https://github.com/berndkuennen/lint_trilogy/tree/master/tiangolo .
