### ISSUE TITLE
How to config the context path

### ISSUE THREAD

**Issue by qiuwei** [tiangolo/uwsgi-nginx-flask-docker#7]
Is there any way to config the app to run at
http://url/my_custom_path

instead of at the root?

**Comment by tiangolo** [comment]
The simplest way would be to prepend your custom URL in the `@app.route()` section.

For example:

```python
from flask import Flask
app = Flask(__name__)

custom_path = '/my_custom_path'

# http://example.com/my_custom_path/
@app.route(custom_path + '/')
def hello_world():
    return 'Hello, World!'

# http://example.com/my_custom_path/test
@app.route(custom_path + '/test')
def hello_test():
    return 'Hello, Test World!'


```
http://flask.pocoo.org/docs/0.12/quickstart/#routing

---

Otherwise, you could configure uWSGI, Nginx, or a proxy before your web app. But any of those choices would be more complicated and would involve configurations in other places with other syntaxes, etc. The simples way to do it in Python is as described above.

Also, if you are using, for example [Rancher](http://rancher.com/) you could add a [load balancer](http://docs.rancher.com/rancher/v1.6/en/cattle/adding-load-balancers/#adding-a-load-balancer-in-the-ui) (they are part of it) and do the configurations there, in a more "graphical" interface.

**Comment by tiangolo** [comment]
As I haven't seen any reply to this, I'll close this issue.

**Comment by Yakuska** [comment]
If you have gunicorn, you can setup your config like this:

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/home/path/to/myproject.sock;

    }
}
