### ISSUE TITLE
Error on :python3.6 at Raspberry Pi 3B+

### ISSUE THREAD

**Issue by ParkDyel** [tiangolo/uwsgi-nginx-flask-docker#75]
I am trying to use "tiangolo / uwsgi-nginx-flask: python3.5 ^" image in Rasberry Pi 3B+(Rasbian strech).
However, can't run with error.
```
standard_init_linux.go: 190: exec user process caused an "exec format error" 
```

I've looked at stackoverflow and found that uwsgi-ngnix-flask is based on uwsgi-nginx, and seems to support raspberry Pi on python3.6.

what am i wrong?

**Comment by andrii1812** [comment]
uwsgi-nginx based on python images that are compiled for x64 arch and not compatible with arm on raspberry. If you want to run python on raspberry you need to use an ARM image as base https://hub.docker.com/r/arm32v7/python/

**Comment by ParkDyel** [comment]
Thanks!

**Comment by tiangolo** [comment]
Thanks @andrii1812 for your help!

---

Here's some more info about it: recently Docker added support for ARM processors (Raspberry Pis, etc). But images have to be compiled for them. Then they added functionality to allow having multi-architecture Dockerfiles, so a Dockerfile could be compiled for any architecture supported. This required some changes in the base Dockerfiles to handle architecture-specific logic, but the Docker team migrated most of the official images. That's why you can actually use a standard Nginx image, or a standard Python image, in a Raspberry Pi.

All those changes were adapted and integrated into these images (`tiangolo/uwsgi-nginx` and `tiangolo/uwsgi-nginx-flask`). So, the Dockerfiles themselves are actually compatible with Raspberry Pi...

**But** these images are compiled using the Docker Hub automated builds. And Docker Hub doesn't support ARM compilation just yet. So, almost everything is in place, except the little last part, from Docker. And that's currently the blocker.

If you want to use these images as your base image, you would have to clone the repository of your base image and this one, build the Docker image inside your Raspberry Pi, and then you would be able to use it as your base image.

If it's a "small project" (you don't expect thousands of users at the same time served by your Raspberry Pi), as of now, it's probably easier to just base your image on the official Python image and use uWSGI directly, without Nginx (installing and configuring both of them might be difficult). uWSGI alone would probably give you a performance "good enough".

**Comment by ParkDyel** [comment]
thanks for your favor and advice.
