### ISSUE TITLE
Why Nginx inside this image?

### ISSUE THREAD

**Issue by vbastos** [tiangolo/uwsgi-nginx-flask-docker#79]
I am doing some research and noticed that you are running Nginx inside this container, which I find strange because I thought most people would already be running a Nginx reverse proxy in front of their applications. I thought it would make more sense just to run a container with just the WSGI application server with the Python application?

**Comment by tiangolo** [comment]
As this issue is from some time ago, I'll assume you were able to fit your requirements. I'll close this issue now.

But feel free to re-open it, add more comments or add new issues.

---

Also, I added a couple of extra sections, about deployment using Docker Swarm and Traefik, links to a couple of project generators, and alternative images (with better performance). If this image doesn't fit your needs, I think one of those might work.
