### ISSUE TITLE
can't send email in flask  docker 

### ISSUE THREAD

**Issue by habout632** [tiangolo/uwsgi-nginx-flask-docker#8]
our smtp server use port 25 as mail server , but we can not  send email  in our container.

**Comment by tiangolo** [comment]
You need to be able to connect to your mail server from the container. If it is another container, it should be in the same network (Docker network) or if it is outside the Docker network, your Flask container needs to be able to communicate / connect to it.

But it's probably a network / firewall / iptables issue.

**Comment by tiangolo** [comment]
As I haven't seen any reply to this in a long time I'll consider it solved and close this issue.

Also, take a look at https://www.mailgun.com/ and https://www.sparkpost.com/

They both have free plans and it's very easy to configure sending emails using their services instead of handling all the complexities of setting up an email server.
