### ISSUE TITLE
Deploying to Elastic Beantalk in AWS?

### ISSUE THREAD

**Issue by gerimo** [tiangolo/uwsgi-nginx-flask-docker#99]
Why have I been getting this error when deploying with Docker to Elastic Beanstalk?

{"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"(TRUNCATED)...pectedly after launch: ile \"/usr/local/lib/python3.6/site-packages/flask_session/sessions.py\", line 23, in <module>\n    from itsdangerous import Signer, BadSignature, want_bytes\nImportError: cannot import name 'want_bytes'. Check snapshot logs for details. \nHook /opt/elasticbeanstalk/hooks/appdeploy/enact/00run.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI","returncode":1,"events":[{"msg":"Successfully built aws_beanstalk/staging-app","severity":"TRACE","timestamp":1540138215},{"msg":"Docker container quit unexpectedly after launch: ile \"/usr/local/lib/python3.6/site-packages/flask_session/sessions.py\", line 23, in <module>\n    from itsdangerous import Signer, BadSignature, want_bytes\nImportError: cannot import name 'want_bytes'. Check snapshot logs for details.","severity":"ERROR","timestamp":1540138226}]}],"truncated":"true"}

**Comment by tiangolo** [comment]
Reading your log, it seems like you are using `flask-session` and that it is generating the error.

Here are my suggestions:

* Make sure Flask-session is compatible with Python 3
* Try starting your container locally in your machine, to discard a problem between Flask-Session and Beanstalk
* As Flask-Session depends on Cookies, make sure you are setting your domain names correctly, as Cookies depend on them. E.g. just an IP probably won't work

---

Now, as an opinionated suggestion, check if you actually need Flask-Session. It might be unnecessary, there are not that many scenarios in where it makes sense to have server-side sessions instead of client-based sessions (as with Cookies alone and tokens).

**Comment by gerimo** [comment]
Yes, you are right
